name: Python-greetings

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/install-pip

  deploy-to-dev:
    runs-on: self-hosted
    needs: [install-pip-deps]
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/python-greetings
          path: theapp
      - uses: ./.github/actions/deploy
        with:
          port: 7001
          environment: dev
          working_dir: theapp

  tests-on-dev:
    runs-on: self-hosted
    needs: [deploy-to-dev]
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/course-js-api-framework
          path: api-tests
      - uses: ./.github/actions/test
        with:
          test_set: greetings
          environment: dev

  deploy-to-staging:
    runs-on: self-hosted
    needs: [tests-on-dev]
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/python-greetings
          path: theapp
      - uses: ./.github/actions/deploy
        with:
          port: 7002
          environment: staging
          working_dir: theapp

  tests-on-staging:
    runs-on: self-hosted
    needs: [deploy-to-staging]
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/course-js-api-framework
          path: api-tests
      - uses: ./.github/actions/test
        with:
          test_set: greetings
          environment: staging

  deploy-to-preprod:
    runs-on: self-hosted
    needs: [tests-on-staging]
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/python-greetings
          path: theapp
      - uses: ./.github/actions/deploy
        with:
          port: 7003
          environment: preprod
          working_dir: theapp

  tests-on-preprod:
    runs-on: self-hosted
    needs: [deploy-to-preprod]
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/course-js-api-framework
          path: api-tests
      - uses: ./.github/actions/test
        with:
          test_set: greetings
          environment: preprod

  deploy-to-prod:
    runs-on: self-hosted
    needs: [tests-on-preprod]
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/python-greetings
          path: theapp
      - uses: ./.github/actions/deploy
        with:
          port: 7004
          environment: prod
          working_dir: theapp

  tests-on-prod:
    runs-on: self-hosted
    needs: [deploy-to-prod]
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/course-js-api-framework
          path: api-tests
      - uses: ./.github/actions/test
        with:
          test_set: greetings
          environment: prod