name: Python-greetings

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/install-pip

  deploy-dev:
    runs-on: self-hosted
    needs: [install-pip-deps]
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/python-greetings
          path: theapp
      - uses: ./.github/actions/deploy
        with:
          port: 7001
          environment: dev
          working_dir: theapp

  test-dev:
    runs-on: self-hosted
    needs: [deploy-dev]
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/course-js-api-framework
          path: api-tests
      - uses: ./.github/actions/test
        with:
          test_set: greetings
          environment: dev