name: Python-greetings

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  install-pip-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/install-pip

  pm2-configuration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/setup-node@v3
      - run: npm install pm2@latest -g
      - run: pm2 -V
      - run: pm2 list

  deploy-dev:
    runs-on: ubuntu-latest
    needs: [install-pip-deps, pm2-configuration]
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/python-greetings
          path: theapp
      - uses: ./.github/actions/deploy
        with:
          port: 7001
          environment: dev
          working_dir: theapp

  test-dev:
    runs-on: ubuntu-latest
    needs: [deploy-dev]
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/course-js-api-framework
          path: js-api-tests
      - uses: ./.github/actions/test
        with:
          environment: dev
          working_dir: js-api-tests
